Sync wiki when running sync action
Signed-off-by: Jiyun Yang <ji.yang@samsung.com>

diff --git a/.github/workflows/github_sync.yml b/.github/workflows/github_sync.yml
--- a/.github/workflows/github_sync.yml
+++ b/.github/workflows/github_sync.yml
@@ -58,6 +58,34 @@ jobs:
               echo "Failed to push dalihub repo"
               exit 1
             fi
+      
+      - name: Sync wiki
+        env:
+          PUBLIC_PAT: ${{ secrets.PAT_TOKEN }}
+        run: |
+          SRC="wiki"
+          DEST="wiki"
+          MAX_RETRIES=3
+          RETRY_COUNT=0
+          SUCCESS=false
+
+          until [ $RETRY_COUNT -ge $MAX_RETRIES ]
+          do
+            if git push public "$SRC:$DEST" --force; then
+              echo "Succeed"
+              SUCCESS=true
+              break
+            else
+              RETRY_COUNT=$((RETRY_COUNT+1))
+              echo "Retry after 5 sec..."
+              sleep 5
+              fi
+            done
+
+            if [ "$SUCCESS" = false ]; then
+              echo "Failed to push dalihub repo"
+              exit 1
+            fi
 
       - name: Sync tags
         env:
